// Behavior coverage for `contract.Spec`'s type-conversion surface: the public
// `getFunc`, `errorCases`, and `scValStrToNative`, plus the UDT paths reached
// through `nativeToScVal` / `scValToNative` (`nativeToUdt`, `nativeToStruct`,
// `nativeToUnion`, `nativeToEnum`, `scValUdtToNative`, `structToNative`,
// `unionToNative`, `enumToNative` — declared `private` in the published `.d.ts`,
// so the public converters are the only way an end user reaches them).
//
// None of these have a test in js-stellar-sdk's suite.
//
// Two fixture sources, deliberately:
//
//   * Hand-built `xdr.ScSpecEntry` values, because a spec exercising every UDT
//     shape (named struct, tuple struct, union, enum, error enum) does not exist
//     as a ready-made artifact. Assertions are against the Soroban ScVal
//     encodings the protocol defines — struct to `scvMap` of symbol keys, tuple
//     struct to `scvVec`, unit enum to `scvU32`, union to `scvVec` led by an
//     `scvSymbol` tag — not against whatever the SDK happens to emit.
//   * The Stellar Asset Contract spec embedded in the SDK, reached the way an
//     application reaches it (`contract.Client.from` against a SAC instance).
//     Those entries were generated by the Rust toolchain, so they anchor
//     `getFunc` and `errorCases` to a spec this repo did not author.
//
// Hostile-input cases matter more than the happy paths here: a spec-aware
// decoder is handed bytes chosen by a contract, and `Spec` is the layer an
// application trusts to interpret them.
import { Contract, contract, scValToNative, xdr } from "@stellar/stellar-sdk";
import { describe, expect, it } from "./helpers/assert.ts";
import { startServer } from "./helpers/server.ts";

const { Client, Spec } = contract;

const SAC_CONTRACT_ID =
  "CCN57TGC6EXFCYIQJ4UCD2UDZ4C3AQCHVMK74DGZ3JYCA5HD4BY7FNPC";
const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";

// --- Spec-entry builders ----------------------------------------------------

const u32 = (): xdr.ScSpecTypeDef => xdr.ScSpecTypeDef.scSpecTypeU32();
const string = (): xdr.ScSpecTypeDef => xdr.ScSpecTypeDef.scSpecTypeString();
const udt = (name: string): xdr.ScSpecTypeDef =>
  xdr.ScSpecTypeDef.scSpecTypeUdt(new xdr.ScSpecTypeUdt({ name }));

function structField(name: string, type: xdr.ScSpecTypeDef) {
  return new xdr.ScSpecUdtStructFieldV0({ doc: "", name, type });
}

function structEntry(
  name: string,
  fields: xdr.ScSpecUdtStructFieldV0[],
): xdr.ScSpecEntry {
  return xdr.ScSpecEntry.scSpecEntryUdtStructV0(
    new xdr.ScSpecUdtStructV0({ doc: "", lib: "", name, fields }),
  );
}

// `Point { x: u32, y: u32 }` — named fields, so it encodes as a map.
const POINT = structEntry("Point", [
  structField("x", u32()),
  structField("y", u32()),
]);

// `Pair(u32, String)` — a Rust tuple struct, whose spec fields are named "0"
// and "1", so it encodes as a vec rather than a map.
const PAIR = structEntry("Pair", [
  structField("0", u32()),
  structField("1", string()),
]);

// Numeric and non-numeric field names together have no valid encoding.
const MIXED = structEntry("Mixed", [
  structField("0", u32()),
  structField("y", u32()),
]);

// Fields declared out of symbol-sort order. Legal in Rust and preserved by the
// spec generator; see the "declaration order" block at the bottom of this file.
const UNSORTED = structEntry("Unsorted", [
  structField("zed", u32()),
  structField("alpha", u32()),
]);

const COLOR = xdr.ScSpecEntry.scSpecEntryUdtEnumV0(
  new xdr.ScSpecUdtEnumV0({
    doc: "",
    lib: "",
    name: "Color",
    cases: [
      new xdr.ScSpecUdtEnumCaseV0({ doc: "", name: "Red", value: 0 }),
      new xdr.ScSpecUdtEnumCaseV0({ doc: "", name: "Blue", value: 7 }),
    ],
  }),
);

const SHAPE = xdr.ScSpecEntry.scSpecEntryUdtUnionV0(
  new xdr.ScSpecUdtUnionV0({
    doc: "",
    lib: "",
    name: "Shape",
    cases: [
      xdr.ScSpecUdtUnionCaseV0.scSpecUdtUnionCaseVoidV0(
        new xdr.ScSpecUdtUnionCaseVoidV0({ doc: "", name: "Empty" }),
      ),
      xdr.ScSpecUdtUnionCaseV0.scSpecUdtUnionCaseTupleV0(
        new xdr.ScSpecUdtUnionCaseTupleV0({
          doc: "",
          name: "Circle",
          type: [u32()],
        }),
      ),
    ],
  }),
);

const ERRORS = xdr.ScSpecEntry.scSpecEntryUdtErrorEnumV0(
  new xdr.ScSpecUdtErrorEnumV0({
    doc: "",
    lib: "",
    name: "Error",
    cases: [
      new xdr.ScSpecUdtErrorEnumCaseV0({ doc: "", name: "NotFound", value: 1 }),
      new xdr.ScSpecUdtErrorEnumCaseV0({ doc: "", name: "Denied", value: 2 }),
    ],
  }),
);

const MOVE = xdr.ScSpecEntry.scSpecEntryFunctionV0(
  new xdr.ScSpecFunctionV0({
    doc: "",
    name: "move",
    inputs: [
      new xdr.ScSpecFunctionInputV0({ doc: "", name: "p", type: udt("Point") }),
    ],
    outputs: [udt("Point")],
  }),
);

const spec = new Spec([POINT, PAIR, MIXED, UNSORTED, COLOR, SHAPE, ERRORS, MOVE]);

/** Reads an `scvMap` back as `[key, value]` symbol/u32 pairs, in wire order. */
function mapPairs(value: xdr.ScVal): [string, number][] {
  const entries = value.map();
  if (entries === null || entries === undefined) {
    throw new Error("expected an scvMap");
  }
  return entries.map((entry) => [
    entry.key().sym().toString(),
    entry.val().u32(),
  ]);
}

function symbolMap(pairs: [string, number][]): xdr.ScVal {
  return xdr.ScVal.scvMap(
    pairs.map(([key, value]) =>
      new xdr.ScMapEntry({
        key: xdr.ScVal.scvSymbol(key),
        val: xdr.ScVal.scvU32(value),
      })
    ),
  );
}

// --- getFunc ----------------------------------------------------------------

describe("stellar-sdk contract.Spec#getFunc", () => {
  it("returns the function spec for a declared function", () => {
    const func = spec.getFunc("move");

    expect(func.name().toString()).toBe("move");
    expect(func.inputs().map((input) => input.name().toString())).toEqual(["p"]);
    expect(func.outputs()).toHaveLength(1);
  });

  it("throws when the named entry exists but is not a function", () => {
    expect(() => spec.getFunc("Point")).toThrow("Point is not a function");
  });

  it("throws when no entry has that name", () => {
    expect(() => spec.getFunc("nonexistent")).toThrow(
      "no such entry: nonexistent",
    );
  });

  // Symbol lookup is exact: a contract cannot be probed with a prefix.
  it("does not match on a prefix of a declared name", () => {
    expect(() => spec.getFunc("mov")).toThrow("no such entry: mov");
    expect(() => spec.getFunc("")).toThrow("no such entry: ");
  });
});

// --- errorCases -------------------------------------------------------------

describe("stellar-sdk contract.Spec#errorCases", () => {
  it("returns every case of the declared error enum", () => {
    const cases = spec.errorCases().map(
      (errorCase) => [errorCase.name().toString(), errorCase.value()],
    );

    expect(cases).toEqual([["NotFound", 1], ["Denied", 2]]);
  });

  it("flattens the cases of every error enum in the spec", () => {
    const second = xdr.ScSpecEntry.scSpecEntryUdtErrorEnumV0(
      new xdr.ScSpecUdtErrorEnumV0({
        doc: "",
        lib: "",
        name: "OtherError",
        cases: [
          new xdr.ScSpecUdtErrorEnumCaseV0({ doc: "", name: "Late", value: 9 }),
        ],
      }),
    );
    const combined = new Spec([ERRORS, second, MOVE]);

    expect(
      combined.errorCases().map((errorCase) => errorCase.name().toString()),
    ).toEqual(["NotFound", "Denied", "Late"]);
  });

  // Only error enums count: a plain `enum` is a value type, not a failure mode.
  it("ignores non-error entries", () => {
    expect(new Spec([POINT, COLOR, SHAPE, MOVE]).errorCases()).toEqual([]);
  });
});

// --- scValStrToNative -------------------------------------------------------

describe("stellar-sdk contract.Spec#scValStrToNative", () => {
  it("decodes a base64 ScVal of a primitive type", () => {
    expect(
      spec.scValStrToNative(xdr.ScVal.scvU32(5).toXDR("base64"), u32()),
    ).toBe(5);
  });

  it("decodes a base64 ScVal of a UDT", () => {
    const encoded = symbolMap([["x", 1], ["y", 2]]).toXDR("base64");

    expect(spec.scValStrToNative(encoded, udt("Point"))).toEqual({ x: 1, y: 2 });
  });

  it("agrees with scValToNative on the same bytes", () => {
    const value = xdr.ScVal.scvString("hello");

    expect(spec.scValStrToNative(value.toXDR("base64"), string())).toBe(
      spec.scValToNative(value, string()),
    );
  });

  it("rejects a string that is not valid ScVal XDR", () => {
    expect(() => spec.scValStrToNative("!!!!", u32())).toThrow("XDR Read Error");
  });

  it("rejects XDR that is truncated mid-value", () => {
    expect(() => spec.scValStrToNative("AAAA", u32())).toThrow("XDR Read Error");
  });
});

// --- native -> ScVal for UDTs (nativeToUdt and friends) ---------------------

describe("stellar-sdk contract.Spec UDT encoding", () => {
  describe("structs", () => {
    it("encodes a named-field struct as a map keyed by field symbols", () => {
      const encoded = spec.nativeToScVal({ x: 1, y: 2 }, udt("Point"));

      expect(encoded.switch().name).toBe("scvMap");
      expect(mapPairs(encoded)).toEqual([["x", 1], ["y", 2]]);
    });

    it("encodes a tuple struct as a vec, dropping the numeric field names", () => {
      const encoded = spec.nativeToScVal([5, "hi"], udt("Pair"));

      expect(encoded.switch().name).toBe("scvVec");
      expect(scValToNative(encoded)).toEqual([5, "hi"]);
    });

    it("rejects a struct mixing numeric and non-numeric field names", () => {
      expect(() => spec.nativeToScVal({ 0: 1, y: 2 }, udt("Mixed"))).toThrow(
        "mixed numeric and non-numeric field names are not allowed",
      );
    });

    it("rejects a value missing a declared field", () => {
      expect(() => spec.nativeToScVal({ x: 1 }, udt("Point"))).toThrow(TypeError);
    });
  });

  describe("unions", () => {
    it("encodes a void case as a single-symbol vec", () => {
      const encoded = spec.nativeToScVal({ tag: "Empty" }, udt("Shape"));
      const items = encoded.vec() ?? [];

      expect(encoded.switch().name).toBe("scvVec");
      expect(items).toHaveLength(1);
      expect(items[0].sym().toString()).toBe("Empty");
    });

    it("encodes a tuple case as the tag symbol followed by its values", () => {
      const encoded = spec.nativeToScVal(
        { tag: "Circle", values: [3] },
        udt("Shape"),
      );
      const items = encoded.vec() ?? [];

      expect(items).toHaveLength(2);
      expect(items[0].sym().toString()).toBe("Circle");
      expect(items[1].u32()).toBe(3);
    });

    it("rejects a tag the union does not declare", () => {
      expect(() => spec.nativeToScVal({ tag: "Nope" }, udt("Shape"))).toThrow(
        "no such enum entry: Nope",
      );
    });

    it("rejects the wrong number of values for a tuple case", () => {
      expect(() =>
        spec.nativeToScVal({ tag: "Circle", values: [1, 2] }, udt("Shape"))
      ).toThrow("expects 1 values, but got 2");
    });
  });

  describe("enums", () => {
    it("encodes a declared case as its u32 discriminant", () => {
      const encoded = spec.nativeToScVal(7, udt("Color"));

      expect(encoded.switch().name).toBe("scvU32");
      expect(encoded.u32()).toBe(7);
    });

    it("rejects a discriminant the enum does not declare", () => {
      expect(() => spec.nativeToScVal(99, udt("Color"))).toThrow(
        "no such enum entry: 99",
      );
    });

    it("rejects a case name in place of its discriminant", () => {
      expect(() => spec.nativeToScVal("Red", udt("Color"))).toThrow(
        "expected number for enum Color, but got string",
      );
    });
  });

  it("rejects a UDT name the spec does not declare", () => {
    expect(() => spec.nativeToScVal({}, udt("Nope"))).toThrow(
      "no such entry: Nope",
    );
  });
});

// --- ScVal -> native for UDTs (scValUdtToNative and friends) ----------------

describe("stellar-sdk contract.Spec UDT decoding", () => {
  it("decodes a struct map back to an object", () => {
    expect(spec.scValToNative(symbolMap([["x", 1], ["y", 2]]), udt("Point")))
      .toEqual({ x: 1, y: 2 });
  });

  it("decodes a tuple-struct vec back to an array", () => {
    const encoded = spec.nativeToScVal([5, "hi"], udt("Pair"));

    expect(spec.scValToNative(encoded, udt("Pair"))).toEqual([5, "hi"]);
  });

  it("decodes a void union case to a bare tag", () => {
    const encoded = xdr.ScVal.scvVec([xdr.ScVal.scvSymbol("Empty")]);

    expect(spec.scValToNative(encoded, udt("Shape"))).toEqual({ tag: "Empty" });
  });

  it("decodes a tuple union case to a tag and its values", () => {
    const encoded = xdr.ScVal.scvVec([
      xdr.ScVal.scvSymbol("Circle"),
      xdr.ScVal.scvU32(3),
    ]);

    expect(spec.scValToNative(encoded, udt("Shape"))).toEqual({
      tag: "Circle",
      values: [3],
    });
  });

  it("decodes an enum discriminant to a number", () => {
    expect(spec.scValToNative(xdr.ScVal.scvU32(7), udt("Color"))).toBe(7);
  });

  describe("rejects malformed encodings", () => {
    it("a non-vec where a union is expected", () => {
      expect(() => spec.scValToNative(xdr.ScVal.scvU32(1), udt("Shape")))
        .toThrow(TypeError);
    });

    it("an empty vec where a union is expected", () => {
      expect(() => spec.scValToNative(xdr.ScVal.scvVec([]), udt("Shape")))
        .toThrow("has length 0");
    });

    it("a union tag that is not a symbol", () => {
      expect(() =>
        spec.scValToNative(
          xdr.ScVal.scvVec([xdr.ScVal.scvU32(1)]),
          udt("Shape"),
        )
      ).toThrow(TypeError);
    });

    it("a union tag the spec does not declare", () => {
      expect(() =>
        spec.scValToNative(
          xdr.ScVal.scvVec([xdr.ScVal.scvSymbol("Nope")]),
          udt("Shape"),
        )
      ).toThrow("failed to find entry Nope in union Shape");
    });

    it("a non-u32 where an enum is expected", () => {
      expect(() => spec.scValToNative(xdr.ScVal.scvString("Red"), udt("Color")))
        .toThrow("Enum must have a u32 value");
    });

    it("a non-map where a struct is expected", () => {
      expect(() => spec.scValToNative(xdr.ScVal.scvVec([]), udt("Point")))
        .toThrow(TypeError);
    });

    it("a UDT name the spec does not declare", () => {
      expect(() => spec.scValToNative(xdr.ScVal.scvU32(1), udt("Nope")))
        .toThrow("no such entry: Nope");
    });
  });
});

// --- Struct decoding is positional -----------------------------------------
//
// `structToNative` walks the incoming map by index and reads the field name from
// the spec at the same index, so the keys in the ScVal are never consulted. That
// is not a hypothetical: Soroban requires ScMap keys to be sorted, while the
// spec lists fields in declaration order, so any contract whose struct fields
// are not declared in sorted order decodes to values under the wrong names.
//
// Pinned as observed behaviour, not endorsed — see ISSUES.md issue 11. If the
// SDK starts matching on keys, these three tests fail, which is the point.
describe("stellar-sdk contract.Spec struct decoding ignores map keys", () => {
  it("assigns values by position when the keys are reordered", () => {
    const reordered = symbolMap([["y", 20], ["x", 10]]);

    // Correct, key-based reading of the same bytes — the SDK's own generic
    // decoder gets this right.
    expect(scValToNative(reordered)).toEqual({ y: 20, x: 10 });

    // DEVIATION: the spec-aware decoder swaps the values.
    expect(spec.scValToNative(reordered, udt("Point"))).toEqual({ x: 20, y: 10 });
  });

  it("accepts keys the struct does not declare, renaming them to declared fields", () => {
    const bogus = symbolMap([["bogus", 42], ["alsoBogus", 43]]);

    // DEVIATION: undeclared keys are neither rejected nor preserved.
    expect(spec.scValToNative(bogus, udt("Point"))).toEqual({ x: 42, y: 43 });
  });

  it("silently drops fields when the map is shorter than the struct", () => {
    const short = symbolMap([["x", 1]]);

    // DEVIATION: `y` is simply absent rather than the decode failing.
    expect(spec.scValToNative(short, udt("Point"))).toEqual({ x: 1 });
  });

  // The concrete consequence, spelled out on a struct whose declaration order
  // and sort order differ. `nativeToScVal` emits declaration order, so a
  // round-trip through this same spec cancels the error out and looks fine —
  // which is why signing and verifying with the same library proves nothing.
  it("round-trips through its own encoder while disagreeing with the wire order", () => {
    const encoded = spec.nativeToScVal({ zed: 1, alpha: 2 }, udt("Unsorted"));

    // Declaration order, not the sorted order an ScMap is required to be in.
    expect(mapPairs(encoded)).toEqual([["zed", 1], ["alpha", 2]]);
    expect(spec.scValToNative(encoded, udt("Unsorted"))).toEqual({
      zed: 1,
      alpha: 2,
    });

    // The same values as a validly sorted ScMap, which is what a network
    // response actually carries.
    const sorted = symbolMap([["alpha", 2], ["zed", 1]]);
    expect(scValToNative(sorted)).toEqual({ alpha: 2, zed: 1 });

    // DEVIATION: read through the spec, the two field values are exchanged.
    expect(spec.scValToNative(sorted, udt("Unsorted"))).toEqual({
      zed: 2,
      alpha: 1,
    });
  });
});

// --- Enum decoding does not validate the discriminant ----------------------
//
// `enumToNative` checks only that the ScVal is a u32; it never looks at the
// declared cases, so encode and decode disagree about which values are legal.
// Pinned as observed behaviour — see ISSUES.md issue 11.
describe("stellar-sdk contract.Spec enum decoding is unvalidated", () => {
  it("accepts a discriminant that the encoder rejects", () => {
    expect(() => spec.nativeToScVal(99, udt("Color"))).toThrow(
      "no such enum entry: 99",
    );

    // DEVIATION: the same value decodes without complaint.
    expect(spec.scValToNative(xdr.ScVal.scvU32(99), udt("Color"))).toBe(99);
  });

  it("does not distinguish one enum from another", () => {
    const other = xdr.ScSpecEntry.scSpecEntryUdtEnumV0(
      new xdr.ScSpecUdtEnumV0({
        doc: "",
        lib: "",
        name: "Other",
        cases: [
          new xdr.ScSpecUdtEnumCaseV0({ doc: "", name: "Only", value: 1 }),
        ],
      }),
    );
    const twoEnums = new Spec([COLOR, other]);

    // DEVIATION: 7 is a Color, not an Other, but both decode identically.
    expect(twoEnums.scValToNative(xdr.ScVal.scvU32(7), udt("Color"))).toBe(7);
    expect(twoEnums.scValToNative(xdr.ScVal.scvU32(7), udt("Other"))).toBe(7);
  });
});

// --- Against a spec this repo did not author --------------------------------
//
// The SDK embeds the Stellar Asset Contract spec, generated by the Rust
// toolchain. An application reaches it by pointing `Client.from` at a SAC, which
// is what the loopback server below stands in for. Using it here keeps `getFunc`
// and `errorCases` honest against entries with an external provenance.
describe("stellar-sdk contract.Spec against the embedded SAC spec", () => {
  async function sacSpec(): Promise<contract.Spec> {
    const address = new Contract(SAC_CONTRACT_ID).address();
    const footprint = new Contract(SAC_CONTRACT_ID).getFootprint();
    const instance = xdr.LedgerEntryData.contractData(
      new xdr.ContractDataEntry({
        ext: new xdr.ExtensionPoint(0),
        contract: address.toScAddress(),
        durability: xdr.ContractDataDurability.persistent(),
        key: xdr.ScVal.scvLedgerKeyContractInstance(),
        val: xdr.ScVal.scvContractInstance(
          new xdr.ScContractInstance({
            executable: xdr.ContractExecutable.contractExecutableStellarAsset(),
            storage: null,
          }),
        ),
      }),
    );

    const server = await startServer(() => ({
      json: {
        jsonrpc: "2.0",
        id: 1,
        result: {
          latestLedger: 100,
          entries: [
            {
              key: footprint.toXDR("base64"),
              xdr: instance.toXDR("base64"),
              lastModifiedLedgerSeq: 1,
              liveUntilLedgerSeq: 1000,
            },
          ],
        },
      },
    }));

    try {
      const client = await Client.from({
        contractId: SAC_CONTRACT_ID,
        networkPassphrase: NETWORK_PASSPHRASE,
        rpcUrl: server.url,
        allowHttp: true,
      });
      return client.spec;
    } finally {
      await server.close();
    }
  }

  // SEP-41 declares `transfer(from: Address, to: Address, amount: i128)`, in
  // that order and with those names.
  it("returns the SEP-41 transfer signature from getFunc", async () => {
    const func = (await sacSpec()).getFunc("transfer");

    expect(func.inputs().map((input) => input.name().toString())).toEqual([
      "from",
      "to",
      "amount",
    ]);
    expect(func.outputs()).toHaveLength(0);
  });

  it("throws for a function the token interface does not define", async () => {
    const sac = await sacSpec();

    expect(() => sac.getFunc("selfDestruct")).toThrow(
      "no such entry: selfDestruct",
    );
  });

  // The SAC exposes no error enum, so this is the empty case measured against a
  // real spec rather than a constructed one.
  it("reports no error cases for the SAC", async () => {
    expect((await sacSpec()).errorCases()).toEqual([]);
  });

  // Function inputs keep declaration order rather than being sorted, which is
  // the evidence that the spec generator preserves source order generally — the
  // premise behind the struct-ordering deviation above.
  it("preserves declaration order in function inputs", async () => {
    const approve = (await sacSpec()).getFunc("approve");
    const names = approve.inputs().map((input) => input.name().toString());

    expect(names).toEqual(["from", "spender", "amount", "expiration_ledger"]);
    expect(names).not.toEqual([...names].sort());
  });
});
